name: Build LaTeX PDF (manual install)

on:
  push:
    paths:
      - "skripts/algebra.tex"
      - ".github/workflows/latex.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-science \
            texlive-lang-german \
            latexmk

      - name: Compile algebra.tex
        run: |
          cd skripts
          latexmk -pdf -interaction=nonstopmode algebra.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: algebra-pdf
          path: skripts/algebra.pdf
